CREATE DATABASE IF NOT EXISTS ira_assets CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ira_assets;
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(150) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, role ENUM('user','admin','super_admin') NOT NULL DEFAULT 'user', status ENUM('active','inactive') NOT NULL DEFAULT 'active', otp_code VARCHAR(16) NULL, otp_expiry DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS laptops (id INT AUTO_INCREMENT PRIMARY KEY, asset_tag VARCHAR(80) NOT NULL UNIQUE, serial_number VARCHAR(120) NOT NULL UNIQUE, brand VARCHAR(100) NOT NULL, model VARCHAR(120) NOT NULL, department VARCHAR(120) NULL, assigned_to INT NULL, status ENUM('Available','Assigned','Maintenance','Retired','Disposed') NOT NULL DEFAULT 'Available', purchase_date DATE NULL, warranty_expiry DATE NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_laptop_user FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS maintenance_records (id INT AUTO_INCREMENT PRIMARY KEY, laptop_id INT NOT NULL, reported_by INT NULL, issue_description TEXT NOT NULL, repair_cost DECIMAL(12,2) NOT NULL DEFAULT 0, repaired_at DATETIME NULL, status ENUM('open','in_progress','resolved') NOT NULL DEFAULT 'open', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE CASCADE, FOREIGN KEY (reported_by) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS approved_areas (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, radius_meters INT NOT NULL DEFAULT 250, active TINYINT(1) NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS device_locations (id BIGINT AUTO_INCREMENT PRIMARY KEY, laptop_id INT NOT NULL, latitude DECIMAL(10,7) NOT NULL, longitude DECIMAL(10,7) NOT NULL, accuracy_meters DECIMAL(10,2) NULL, captured_at DATETIME NOT NULL, source ENUM('browser','managed_client') NOT NULL DEFAULT 'browser', consent_status ENUM('granted','withdrawn') NOT NULL DEFAULT 'granted', created_by INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_location_laptop_time (laptop_id, captured_at), FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE CASCADE, FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT);
CREATE TABLE IF NOT EXISTS location_alerts (id BIGINT AUTO_INCREMENT PRIMARY KEY, laptop_id INT NOT NULL, location_id BIGINT NOT NULL, message VARCHAR(255) NOT NULL, status ENUM('open','acknowledged') NOT NULL DEFAULT 'open', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE CASCADE, FOREIGN KEY (location_id) REFERENCES device_locations(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL, action VARCHAR(80) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id BIGINT NULL, metadata JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_entity (entity_type, entity_id), FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);
